### ISSUE TITLE
Пропущена запятая

### ISSUE THREAD

**Issue by EvgeniyZ** [DotNetRu/DotNetRu.github.io#24]
В параграфе 

<p>Мы вместе разрабатываем различные проекты на GitHub и всегда ищем тех, кто может помочь сообществу не только словом но и кодом.</p>

в конце предложения пропущена запятая. Нужно так:

<p>Мы вместе разрабатываем различные проекты на GitHub и всегда ищем тех, кто может помочь сообществу не только словом, но и кодом.</p>

**Comment by AnatolyKulakov** [comment]
Спасибо. Вмёржил #25
